[env:wt32-sc01-plus]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.partitions = default_8MB.csv
board_build.flash_size = 8MB
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.psram_enabled = true

monitor_speed = 115200
monitor_port = COM3

lib_extra_dirs = lib

lib_deps = 
    lovyan03/LovyanGFX@^1.2.19
    lvgl/lvgl@^8.3.11
    lib/ENS160_driver-master
    lib/SparkFun_BMP180
    lib/SparkFun_Indoor_Air_Quality_Sensor-ENS160_Arduino_Library-main
    lib/SparkFun_Qwiic_Humidity_AHT20_Arduino_Library-main
    lib/Rtc_by_Makuna

; ====================== КРИТИЧНЫЕ ФЛАГИ ======================
build_flags =
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -D LV_CONF_INCLUDE_SIMPLE
    -I src
    -D LV_COLOR_DEPTH=16
    -D LV_COLOR_16_SWAP=0
    -D LV_MEM_SIZE="(96U * 1024U)"     

    ; ====================== Пути include  ======================
    -I src
    -I src/converter
    -I src/ui
    -I src/ui/screens
    -I src/ui/imgWeather
    -I src/sensors
    -I src/rtc
    -I src/location
    -I src/weather_forecast
    -I src/ntp
    -I src/connections
    -I src/globals
    -I lib/SparkFun_BMP180/src
    -I lib/SparkFun_Indoor_Air_Quality_Sensor-ENS160_Arduino_Library-main/src
    -I lib/SparkFun_Qwiic_Humidity_AHT20_Arduino_Library-main/src
    -I lib/ENS160_driver-master/src
    -I lib/Rtc_by_Makuna/src
    

