// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ///////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ///////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ///////////////////

///////////////////// FUNCTIONS ///////////////////

///////////////////// SCREENS ///////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_OptionsScreen_screen_init();
    ui_SensorsDataScreen_screen_init();
    ui_WeatherScreen_screen_init();
    ui_WiFiScreen_screen_init();
    ui_BrightnessScreen_screen_init();
    ui_DateTimeScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);

    // мои обработчики из ui.c
    lv_obj_add_event_cb(ui_Wifisw, Wifisw_event_handler, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_ClearWifibtn, ClearWifibtn_event_handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_brightnessslider, brightness_slider_event_handler, LV_EVENT_VALUE_CHANGED, NULL);
    
    lv_obj_add_event_cb(ui_AplyDateTimeBtn, DateTimeSaveBtn_event_handler, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_DateTimeScreen, DateTimeScreen_loaded_event_handler, LV_EVENT_SCREEN_LOADED, NULL);
    
    // ДОБАВИТЬ ОБРАБОТЧИК ДЛЯ КАЛЕНДАРЯ
    lv_obj_add_event_cb(ui_Calendar, Calendar_event_handler, LV_EVENT_VALUE_CHANGED, NULL);
}

void ui_destroy(void)
{
    ui_MainScreen_screen_destroy();
    ui_OptionsScreen_screen_destroy();
    ui_SensorsDataScreen_screen_destroy();
    ui_WeatherScreen_screen_destroy();
    ui_WiFiScreen_screen_destroy();
    ui_BrightnessScreen_screen_destroy();
    ui_DateTimeScreen_screen_destroy();
}