// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#ifndef _WT32_SC01_PLUS_UI_H
#define _WT32_SC01_PLUS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MainScreen.h"
#include "screens/ui_OptionsScreen.h"
#include "screens/ui_SensorsDataScreen.h"
#include "screens/ui_WeatherScreen.h"
#include "screens/ui_WiFiScreen.h"
#include "screens/ui_BrightnessScreen.h"
#include "screens/ui_DateTimeScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_temphum_png);    // assets/temphum.png
LV_IMG_DECLARE(ui_img_1410116608);    // assets/04n_t@2x.png
LV_IMG_DECLARE(ui_img_pinpoint_png);    // assets/pinpoint.png
LV_IMG_DECLARE(ui_img_wifioffimg_png);    // assets/wifioffimg.png
LV_IMG_DECLARE(ui_img_wifionimg_png);    // assets/wifionimg.png
LV_IMG_DECLARE(ui_img_03d_t_png);    // assets/03d_t.png
LV_IMG_DECLARE(ui_img_177211067);    // assets/icons8-eco-indicator-32.png
LV_IMG_DECLARE(ui_img_83639835);    // assets/icons8-settings-32.png
LV_IMG_DECLARE(ui_img_1803534315);    // assets/icons8-back-50.png
LV_IMG_DECLARE(ui_img_barometer_png);    // assets/barometer.png
LV_IMG_DECLARE(ui_img_1387918458);    // assets/icons8-high-tide-48.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
