// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

//мои обработчики событий в ui_events.h
void Wifisw_event_handler(lv_event_t * e);
void ClearWifibtn_event_handler(lv_event_t * e);

void brightness_slider_event_handler(lv_event_t * e);

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
