// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#include "../ui.h"

lv_obj_t * ui_BrightnessScreen = NULL;
lv_obj_t * ui_backbtn2 = NULL;
lv_obj_t * ui_brightnessslider = NULL;
lv_obj_t * ui_BrightnessText = NULL;
lv_obj_t * ui_percentagetext1 = NULL;
// event funtions
void ui_event_backbtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_OptionsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_OptionsScreen_screen_init);
    }
}

// build funtions

void ui_BrightnessScreen_screen_init(void)
{
    ui_BrightnessScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BrightnessScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_BrightnessScreen, lv_color_hex(0x181C18), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessScreen, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_backbtn2 = lv_img_create(ui_BrightnessScreen);
    lv_img_set_src(ui_backbtn2, &ui_img_1803534315);
    lv_obj_set_width(ui_backbtn2, 50);
    lv_obj_set_height(ui_backbtn2, 50);
    lv_obj_set_x(ui_backbtn2, -190);
    lv_obj_set_y(ui_backbtn2, 135);
    lv_obj_set_align(ui_backbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_backbtn2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_primaryBlue);
    ui_object_set_themeable_style_property(ui_backbtn2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_primaryBlue);

    ui_brightnessslider = lv_slider_create(ui_BrightnessScreen);
    lv_slider_set_range(ui_brightnessslider, 0, 255);
    lv_slider_set_value(ui_brightnessslider, 255, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_brightnessslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_brightnessslider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_brightnessslider, 400);
    lv_obj_set_height(ui_brightnessslider, 20);
    lv_obj_set_x(ui_brightnessslider, 0);
    lv_obj_set_y(ui_brightnessslider, -24);
    lv_obj_set_align(ui_brightnessslider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_brightnessslider, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessslider, 219, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_brightnessslider, lv_color_hex(0x2196F3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessslider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_brightnessslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessslider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BrightnessText = lv_label_create(ui_BrightnessScreen);
    lv_obj_set_width(ui_BrightnessText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessText, -5);
    lv_obj_set_y(ui_BrightnessText, -60);
    lv_obj_set_align(ui_BrightnessText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessText, "100");
    lv_obj_set_style_text_font(ui_BrightnessText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percentagetext1 = lv_label_create(ui_BrightnessScreen);
    lv_obj_set_width(ui_percentagetext1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percentagetext1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_percentagetext1, 27);
    lv_obj_set_y(ui_percentagetext1, -60);
    lv_obj_set_align(ui_percentagetext1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percentagetext1, "%");
    lv_obj_set_style_text_font(ui_percentagetext1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backbtn2, ui_event_backbtn2, LV_EVENT_ALL, NULL);

}

void ui_BrightnessScreen_screen_destroy(void)
{
    if(ui_BrightnessScreen) lv_obj_del(ui_BrightnessScreen);

    // NULL screen variables
    ui_BrightnessScreen = NULL;
    ui_backbtn2 = NULL;
    ui_brightnessslider = NULL;
    ui_BrightnessText = NULL;
    ui_percentagetext1 = NULL;

}
