// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#ifndef UI_BRIGHTNESSSCREEN_H
#define UI_BRIGHTNESSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BrightnessScreen
extern void ui_BrightnessScreen_screen_init(void);
extern void ui_BrightnessScreen_screen_destroy(void);
extern lv_obj_t * ui_BrightnessScreen;
extern void ui_event_backbtn2(lv_event_t * e);
extern lv_obj_t * ui_backbtn2;
extern lv_obj_t * ui_brightnessslider;
extern lv_obj_t * ui_BrightnessText;
extern lv_obj_t * ui_percentagetext1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

