// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#include "../ui.h"

lv_obj_t * ui_DateTimeScreen = NULL;
lv_obj_t * ui_backbtn5 = NULL;
lv_obj_t * ui_DatePanel = NULL;
lv_obj_t * ui_Calendar = NULL;
lv_obj_t * ui_TimePanel = NULL;
lv_obj_t * ui_hourRoller = NULL;
lv_obj_t * ui_separator2 = NULL;
lv_obj_t * ui_minuteRoller = NULL;
lv_obj_t * ui_AplyDateTimeBtn = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_backbtn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_OptionsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_OptionsScreen_screen_init);
    }
}

// build funtions

void ui_DateTimeScreen_screen_init(void)
{
    ui_DateTimeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DateTimeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_DateTimeScreen, lv_color_hex(0x181C18), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DateTimeScreen, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_backbtn5 = lv_img_create(ui_DateTimeScreen);
    lv_img_set_src(ui_backbtn5, &ui_img_1803534315);
    lv_obj_set_width(ui_backbtn5, 50);
    lv_obj_set_height(ui_backbtn5, 50);
    lv_obj_set_x(ui_backbtn5, -190);
    lv_obj_set_y(ui_backbtn5, 135);
    lv_obj_set_align(ui_backbtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backbtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_backbtn5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_primaryBlue);
    ui_object_set_themeable_style_property(ui_backbtn5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_primaryBlue);

    ui_DatePanel = lv_obj_create(ui_DateTimeScreen);
    lv_obj_set_width(ui_DatePanel, 220);
    lv_obj_set_height(ui_DatePanel, 220);
    lv_obj_set_x(ui_DatePanel, 5);
    lv_obj_set_y(ui_DatePanel, 20);
    lv_obj_clear_flag(ui_DatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar = lv_calendar_create(ui_DatePanel);
    lv_obj_t * ui_Calendar_header = lv_calendar_header_arrow_create(ui_Calendar);
    lv_obj_set_width(ui_Calendar, 200);
    lv_obj_set_height(ui_Calendar, 200);
    lv_obj_set_align(ui_Calendar, LV_ALIGN_CENTER);

    ui_TimePanel = lv_obj_create(ui_DateTimeScreen);
    lv_obj_set_width(ui_TimePanel, 240);
    lv_obj_set_height(ui_TimePanel, 100);
    lv_obj_set_x(ui_TimePanel, -10);
    lv_obj_set_y(ui_TimePanel, 20);
    lv_obj_set_align(ui_TimePanel, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_TimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hourRoller = lv_roller_create(ui_TimePanel);
    lv_roller_set_options(ui_hourRoller,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_hourRoller, 80);
    lv_obj_set_height(ui_hourRoller, 100);
    lv_obj_set_align(ui_hourRoller, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_hourRoller, lv_color_hex(0x181C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_hourRoller, lv_color_hex(0x2196F3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_separator2 = lv_label_create(ui_TimePanel);
    lv_obj_set_width(ui_separator2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_separator2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_separator2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_separator2, ":");
    lv_obj_set_style_text_letter_space(ui_separator2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_separator2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_separator2, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minuteRoller = lv_roller_create(ui_TimePanel);
    lv_roller_set_options(ui_minuteRoller,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_minuteRoller, 80);
    lv_obj_set_height(ui_minuteRoller, 100);
    lv_obj_set_align(ui_minuteRoller, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_minuteRoller, lv_color_hex(0x181C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minuteRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_minuteRoller, lv_color_hex(0x2196F3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minuteRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_AplyDateTimeBtn = lv_btn_create(ui_DateTimeScreen);
    lv_obj_set_width(ui_AplyDateTimeBtn, 240);
    lv_obj_set_height(ui_AplyDateTimeBtn, 50);
    lv_obj_set_x(ui_AplyDateTimeBtn, -10);
    lv_obj_set_y(ui_AplyDateTimeBtn, -80);
    lv_obj_set_align(ui_AplyDateTimeBtn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_AplyDateTimeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AplyDateTimeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_AplyDateTimeBtn);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Save");

    lv_obj_add_event_cb(ui_backbtn5, ui_event_backbtn5, LV_EVENT_ALL, NULL);

    

}

void ui_DateTimeScreen_screen_destroy(void)
{
    if(ui_DateTimeScreen) lv_obj_del(ui_DateTimeScreen);

    // NULL screen variables
    ui_DateTimeScreen = NULL;
    ui_backbtn5 = NULL;
    ui_DatePanel = NULL;
    ui_Calendar = NULL;
    ui_TimePanel = NULL;
    ui_hourRoller = NULL;
    ui_separator2 = NULL;
    ui_minuteRoller = NULL;
    ui_AplyDateTimeBtn = NULL;
    ui_Label2 = NULL;

}
