// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#ifndef UI_DATETIMESCREEN_H
#define UI_DATETIMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DateTimeScreen
extern void ui_DateTimeScreen_screen_init(void);
extern void ui_DateTimeScreen_screen_destroy(void);
extern lv_obj_t * ui_DateTimeScreen;
extern void ui_event_backbtn5(lv_event_t * e);
extern lv_obj_t * ui_backbtn5;
extern lv_obj_t * ui_DatePanel;
extern lv_obj_t * ui_Calendar;
extern lv_obj_t * ui_TimePanel;
extern lv_obj_t * ui_hourRoller;
extern lv_obj_t * ui_separator2;
extern lv_obj_t * ui_minuteRoller;
extern lv_obj_t * ui_AplyDateTimeBtn;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

