// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#include "../ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_MainScreenPanel = NULL;
lv_obj_t * ui_dummytext = NULL;
lv_obj_t * ui_hour = NULL;
lv_obj_t * ui_minute = NULL;
lv_obj_t * ui_separator = NULL;
lv_obj_t * ui_TempHumAPI = NULL;
lv_obj_t * ui_tempAPIlbl = NULL;
lv_obj_t * ui_humAPIlbl = NULL;
lv_obj_t * ui_temphumimg = NULL;
lv_obj_t * ui_WeatherMainScreenPanel = NULL;
lv_obj_t * ui_WeatherOnMainScreenImg = NULL;
lv_obj_t * ui_weatherInfoMainScreenLabel = NULL;
lv_obj_t * ui_ControlPanel = NULL;
lv_obj_t * ui_pinpointimg = NULL;
lv_obj_t * ui_locationtext = NULL;
lv_obj_t * ui_wifioffimg = NULL;
lv_obj_t * ui_wifionimg = NULL;
lv_obj_t * ui_weatherbtn = NULL;
lv_obj_t * ui_sensorsbtn = NULL;
lv_obj_t * ui_optionsbtn = NULL;
lv_obj_t * ui_datetext = NULL;
// event funtions
void ui_event_MainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_OptionsScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 100, 0, &ui_OptionsScreen_screen_init);
    }
}

void ui_event_wifioffimg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_WiFiScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_WiFiScreen_screen_init);
    }
}

void ui_event_wifionimg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_WiFiScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_WiFiScreen_screen_init);
    }
}

void ui_event_weatherbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_WeatherScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_WeatherScreen_screen_init);
    }
}

void ui_event_sensorsbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_SensorsDataScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_SensorsDataScreen_screen_init);
    }
}

void ui_event_optionsbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_OptionsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_OptionsScreen_screen_init);
    }
}

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainScreenPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_MainScreenPanel, 480);
    lv_obj_set_height(ui_MainScreenPanel, 320);
    lv_obj_set_align(ui_MainScreenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainScreenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainScreenPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainScreenPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MainScreenPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MainScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dummytext = lv_label_create(ui_MainScreenPanel);
    lv_obj_set_width(ui_dummytext, lv_pct(60));
    lv_obj_set_height(ui_dummytext, lv_pct(20));
    lv_obj_set_x(ui_dummytext, 0);
    lv_obj_set_y(ui_dummytext, -54);
    lv_obj_set_align(ui_dummytext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dummytext, "       ");
    lv_obj_set_style_text_letter_space(ui_dummytext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_dummytext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dummytext, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_dummytext, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dummytext, lv_color_hex(0x044273), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dummytext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_dummytext, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_primaryBlue);
    lv_obj_set_style_bg_grad_dir(ui_dummytext, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dummytext, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dummytext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dummytext, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dummytext, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour = lv_label_create(ui_MainScreenPanel);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, -80);
    lv_obj_set_y(ui_hour, -55);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "23");
    lv_obj_set_style_text_letter_space(ui_hour, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minute = lv_label_create(ui_MainScreenPanel);
    lv_obj_set_width(ui_minute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minute, 75);
    lv_obj_set_y(ui_minute, -55);
    lv_obj_set_align(ui_minute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minute, "59");
    lv_obj_set_style_text_letter_space(ui_minute, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_minute, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minute, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_separator = lv_label_create(ui_MainScreenPanel);
    lv_obj_set_width(ui_separator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_separator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_separator, 0);
    lv_obj_set_y(ui_separator, -57);
    lv_obj_set_align(ui_separator, LV_ALIGN_CENTER);
    lv_label_set_text(ui_separator, ":");
    lv_obj_set_style_text_letter_space(ui_separator, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_separator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_separator, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempHumAPI = lv_obj_create(ui_MainScreenPanel);
    lv_obj_set_width(ui_TempHumAPI, 100);
    lv_obj_set_height(ui_TempHumAPI, 50);
    lv_obj_set_x(ui_TempHumAPI, -190);
    lv_obj_set_y(ui_TempHumAPI, 135);
    lv_obj_set_align(ui_TempHumAPI, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempHumAPI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TempHumAPI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempHumAPI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempHumAPI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TempHumAPI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempAPIlbl = lv_label_create(ui_TempHumAPI);
    lv_obj_set_width(ui_tempAPIlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempAPIlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempAPIlbl, 12);
    lv_obj_set_y(ui_tempAPIlbl, -13);
    lv_obj_set_align(ui_tempAPIlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempAPIlbl, "0.1");
    lv_obj_set_style_text_font(ui_tempAPIlbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humAPIlbl = lv_label_create(ui_TempHumAPI);
    lv_obj_set_width(ui_humAPIlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humAPIlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humAPIlbl, 12);
    lv_obj_set_y(ui_humAPIlbl, 14);
    lv_obj_set_align(ui_humAPIlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humAPIlbl, "71");
    lv_obj_set_style_text_font(ui_humAPIlbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temphumimg = lv_img_create(ui_TempHumAPI);
    lv_img_set_src(ui_temphumimg, &ui_img_temphum_png);
    lv_obj_set_width(ui_temphumimg, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_temphumimg, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_temphumimg, -28);
    lv_obj_set_y(ui_temphumimg, -1);
    lv_obj_set_align(ui_temphumimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temphumimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temphumimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_temphumimg, 100);

    ui_WeatherMainScreenPanel = lv_obj_create(ui_MainScreenPanel);
    lv_obj_set_height(ui_WeatherMainScreenPanel, 192);
    lv_obj_set_width(ui_WeatherMainScreenPanel, lv_pct(60));
    lv_obj_set_x(ui_WeatherMainScreenPanel, 0);
    lv_obj_set_y(ui_WeatherMainScreenPanel, 60);
    lv_obj_set_align(ui_WeatherMainScreenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WeatherMainScreenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WeatherMainScreenPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherMainScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WeatherMainScreenPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WeatherMainScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherOnMainScreenImg = lv_img_create(ui_WeatherMainScreenPanel);
    lv_img_set_src(ui_WeatherOnMainScreenImg, &ui_img_1410116608);
    lv_obj_set_width(ui_WeatherOnMainScreenImg, LV_SIZE_CONTENT);   /// 360
    lv_obj_set_height(ui_WeatherOnMainScreenImg, LV_SIZE_CONTENT);    /// 360
    lv_obj_set_x(ui_WeatherOnMainScreenImg, 0);
    lv_obj_set_y(ui_WeatherOnMainScreenImg, -2);
    lv_obj_set_align(ui_WeatherOnMainScreenImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherOnMainScreenImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WeatherOnMainScreenImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WeatherOnMainScreenImg, 400);

    ui_weatherInfoMainScreenLabel = lv_label_create(ui_WeatherMainScreenPanel);
    lv_obj_set_width(ui_weatherInfoMainScreenLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherInfoMainScreenLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherInfoMainScreenLabel, 3);
    lv_obj_set_y(ui_weatherInfoMainScreenLabel, 87);
    lv_obj_set_align(ui_weatherInfoMainScreenLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherInfoMainScreenLabel, "Broken clouds");
    lv_obj_set_style_text_align(ui_weatherInfoMainScreenLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherInfoMainScreenLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_weatherInfoMainScreenLabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weatherInfoMainScreenLabel, lv_color_hex(0x474113), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weatherInfoMainScreenLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_weatherInfoMainScreenLabel, lv_color_hex(0x887403), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_weatherInfoMainScreenLabel, lv_color_hex(0x887403), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_weatherInfoMainScreenLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_weatherInfoMainScreenLabel, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_weatherInfoMainScreenLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ControlPanel = lv_obj_create(ui_MainScreenPanel);
    lv_obj_set_height(ui_ControlPanel, 64);
    lv_obj_set_width(ui_ControlPanel, lv_pct(100));
    lv_obj_set_x(ui_ControlPanel, 0);
    lv_obj_set_y(ui_ControlPanel, -20);
    lv_obj_set_align(ui_ControlPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ControlPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ControlPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ControlPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ControlPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_ControlPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_pinpointimg = lv_img_create(ui_ControlPanel);
    lv_img_set_src(ui_pinpointimg, &ui_img_pinpoint_png);
    lv_obj_set_width(ui_pinpointimg, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_pinpointimg, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_pinpointimg, -215);
    lv_obj_set_y(ui_pinpointimg, 0);
    lv_obj_set_align(ui_pinpointimg, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_pinpointimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pinpointimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_pinpointimg, 20);

    ui_locationtext = lv_label_create(ui_ControlPanel);
    lv_obj_set_width(ui_locationtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_locationtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_locationtext, 5);
    lv_obj_set_y(ui_locationtext, 0);
    lv_obj_set_align(ui_locationtext, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_locationtext, "Yekaterinburg");
    lv_obj_set_style_text_font(ui_locationtext, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifioffimg = lv_img_create(ui_ControlPanel);
    lv_img_set_src(ui_wifioffimg, &ui_img_wifioffimg_png);
    lv_obj_set_width(ui_wifioffimg, LV_SIZE_CONTENT);   /// 125
    lv_obj_set_height(ui_wifioffimg, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_wifioffimg, -1);
    lv_obj_set_y(ui_wifioffimg, -55);
    lv_obj_set_align(ui_wifioffimg, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_wifioffimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifioffimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_wifioffimg, 80);
    ui_object_set_themeable_style_property(ui_wifioffimg, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_primaryBlue);
    ui_object_set_themeable_style_property(ui_wifioffimg, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_primaryBlue);

    ui_wifionimg = lv_img_create(ui_ControlPanel);
    lv_img_set_src(ui_wifionimg, &ui_img_wifionimg_png);
    lv_obj_set_width(ui_wifionimg, LV_SIZE_CONTENT);   /// 125
    lv_obj_set_height(ui_wifionimg, LV_SIZE_CONTENT);    /// 125
    lv_obj_set_x(ui_wifionimg, -1);
    lv_obj_set_y(ui_wifionimg, -10);
    lv_obj_set_align(ui_wifionimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifionimg, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifionimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_wifionimg, 80);
    ui_object_set_themeable_style_property(ui_wifionimg, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_primaryBlue);
    ui_object_set_themeable_style_property(ui_wifionimg, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_primaryBlue);

    ui_weatherbtn = lv_imgbtn_create(ui_ControlPanel);
    lv_imgbtn_set_src(ui_weatherbtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_03d_t_png, NULL);
    lv_obj_set_width(ui_weatherbtn, 50);
    lv_obj_set_height(ui_weatherbtn, 50);
    lv_obj_set_x(ui_weatherbtn, -75);
    lv_obj_set_y(ui_weatherbtn, -1);
    lv_obj_set_align(ui_weatherbtn, LV_ALIGN_RIGHT_MID);
    ui_object_set_themeable_style_property(ui_weatherbtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_primaryBlue);
    ui_object_set_themeable_style_property(ui_weatherbtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_primaryBlue);

    ui_sensorsbtn = lv_imgbtn_create(ui_ControlPanel);
    lv_imgbtn_set_src(ui_sensorsbtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_177211067, NULL);
    lv_obj_set_width(ui_sensorsbtn, 32);
    lv_obj_set_height(ui_sensorsbtn, 32);
    lv_obj_set_x(ui_sensorsbtn, -40);
    lv_obj_set_y(ui_sensorsbtn, 0);
    lv_obj_set_align(ui_sensorsbtn, LV_ALIGN_RIGHT_MID);
    ui_object_set_themeable_style_property(ui_sensorsbtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_primaryBlue);
    ui_object_set_themeable_style_property(ui_sensorsbtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_primaryBlue);

    ui_optionsbtn = lv_imgbtn_create(ui_ControlPanel);
    lv_imgbtn_set_src(ui_optionsbtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_83639835, NULL);
    lv_obj_set_width(ui_optionsbtn, 32);
    lv_obj_set_height(ui_optionsbtn, 32);
    lv_obj_set_x(ui_optionsbtn, 2);
    lv_obj_set_y(ui_optionsbtn, 0);
    lv_obj_set_align(ui_optionsbtn, LV_ALIGN_RIGHT_MID);
    ui_object_set_themeable_style_property(ui_optionsbtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_primaryBlue);
    ui_object_set_themeable_style_property(ui_optionsbtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_primaryBlue);

    ui_datetext = lv_label_create(ui_MainScreenPanel);
    lv_obj_set_width(ui_datetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_datetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_datetext, 186);
    lv_obj_set_y(ui_datetext, 144);
    lv_obj_set_align(ui_datetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_datetext, "2024.01.01");
    lv_obj_set_style_text_font(ui_datetext, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_wifioffimg, ui_event_wifioffimg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifionimg, ui_event_wifionimg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_weatherbtn, ui_event_weatherbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sensorsbtn, ui_event_sensorsbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_optionsbtn, ui_event_optionsbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_MainScreenPanel = NULL;
    ui_dummytext = NULL;
    ui_hour = NULL;
    ui_minute = NULL;
    ui_separator = NULL;
    ui_TempHumAPI = NULL;
    ui_tempAPIlbl = NULL;
    ui_humAPIlbl = NULL;
    ui_temphumimg = NULL;
    ui_WeatherMainScreenPanel = NULL;
    ui_WeatherOnMainScreenImg = NULL;
    ui_weatherInfoMainScreenLabel = NULL;
    ui_ControlPanel = NULL;
    ui_pinpointimg = NULL;
    ui_locationtext = NULL;
    ui_wifioffimg = NULL;
    ui_wifionimg = NULL;
    ui_weatherbtn = NULL;
    ui_sensorsbtn = NULL;
    ui_optionsbtn = NULL;
    ui_datetext = NULL;

}
