// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_MainScreenPanel;
extern lv_obj_t * ui_dummytext;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_minute;
extern lv_obj_t * ui_separator;
extern lv_obj_t * ui_TempHumAPI;
extern lv_obj_t * ui_tempAPIlbl;
extern lv_obj_t * ui_humAPIlbl;
extern lv_obj_t * ui_temphumimg;
extern lv_obj_t * ui_WeatherMainScreenPanel;
extern lv_obj_t * ui_WeatherOnMainScreenImg;
extern lv_obj_t * ui_weatherInfoMainScreenLabel;
extern lv_obj_t * ui_ControlPanel;
extern lv_obj_t * ui_pinpointimg;
extern lv_obj_t * ui_locationtext;
extern void ui_event_wifioffimg(lv_event_t * e);
extern lv_obj_t * ui_wifioffimg;
extern void ui_event_wifionimg(lv_event_t * e);
extern lv_obj_t * ui_wifionimg;
extern void ui_event_weatherbtn(lv_event_t * e);
extern lv_obj_t * ui_weatherbtn;
extern void ui_event_sensorsbtn(lv_event_t * e);
extern lv_obj_t * ui_sensorsbtn;
extern void ui_event_optionsbtn(lv_event_t * e);
extern lv_obj_t * ui_optionsbtn;
extern lv_obj_t * ui_datetext;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

