// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#ifndef UI_OPTIONSSCREEN_H
#define UI_OPTIONSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_OptionsScreen
extern void ui_OptionsScreen_screen_init(void);
extern void ui_OptionsScreen_screen_destroy(void);
extern void ui_event_OptionsScreen(lv_event_t * e);
extern lv_obj_t * ui_OptionsScreen;
extern lv_obj_t * ui_OptionsScreenPanel;
extern void ui_event_WiFiPanel(lv_event_t * e);
extern lv_obj_t * ui_WiFiPanel;
extern void ui_event_WiFiOptionsText(lv_event_t * e);
extern lv_obj_t * ui_WiFiOptionsText;
extern void ui_event_BrightnessPanel(lv_event_t * e);
extern lv_obj_t * ui_BrightnessPanel;
extern void ui_event_BrightnessAndjustText(lv_event_t * e);
extern lv_obj_t * ui_BrightnessAndjustText;
extern void ui_event_DateTimePanel(lv_event_t * e);
extern lv_obj_t * ui_DateTimePanel;
extern void ui_event_DateTimeText(lv_event_t * e);
extern lv_obj_t * ui_DateTimeText;
extern void ui_event_backbtn3(lv_event_t * e);
extern lv_obj_t * ui_backbtn3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

