// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#include "../ui.h"

lv_obj_t * ui_OptionsScreen = NULL;
lv_obj_t * ui_OptionsScreenPanel = NULL;
lv_obj_t * ui_WiFiPanel = NULL;
lv_obj_t * ui_WiFiOptionsText = NULL;
lv_obj_t * ui_BrightnessPanel = NULL;
lv_obj_t * ui_BrightnessAndjustText = NULL;
lv_obj_t * ui_DateTimePanel = NULL;
lv_obj_t * ui_DateTimeText = NULL;
lv_obj_t * ui_backbtn3 = NULL;
// event funtions
void ui_event_OptionsScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 100, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_WiFiPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_WiFiScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_WiFiScreen_screen_init);
    }
}

void ui_event_WiFiOptionsText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_WiFiScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_WiFiScreen_screen_init);
    }
}

void ui_event_BrightnessPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_BrightnessScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_BrightnessScreen_screen_init);
    }
}

void ui_event_BrightnessAndjustText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_BrightnessScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_BrightnessScreen_screen_init);
    }
}

void ui_event_DateTimePanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_DateTimeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_DateTimeScreen_screen_init);
    }
}

void ui_event_DateTimeText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_BrightnessScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_BrightnessScreen_screen_init);
    }
}

void ui_event_backbtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_MainScreen_screen_init);
    }
}

// build funtions

void ui_OptionsScreen_screen_init(void)
{
    ui_OptionsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OptionsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OptionsScreenPanel = lv_obj_create(ui_OptionsScreen);
    lv_obj_set_width(ui_OptionsScreenPanel, 480);
    lv_obj_set_height(ui_OptionsScreenPanel, 320);
    lv_obj_set_align(ui_OptionsScreenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OptionsScreenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_OptionsScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OptionsScreenPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OptionsScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiPanel = lv_obj_create(ui_OptionsScreenPanel);
    lv_obj_set_width(ui_WiFiPanel, 421);
    lv_obj_set_height(ui_WiFiPanel, 29);
    lv_obj_set_x(ui_WiFiPanel, 0);
    lv_obj_set_y(ui_WiFiPanel, -83);
    lv_obj_set_align(ui_WiFiPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WiFiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiOptionsText = lv_label_create(ui_WiFiPanel);
    lv_obj_set_width(ui_WiFiOptionsText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiOptionsText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFiOptionsText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiOptionsText, "WiFi");
    lv_obj_set_style_text_font(ui_WiFiOptionsText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessPanel = lv_obj_create(ui_OptionsScreenPanel);
    lv_obj_set_width(ui_BrightnessPanel, 421);
    lv_obj_set_height(ui_BrightnessPanel, 29);
    lv_obj_set_align(ui_BrightnessPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrightnessPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessAndjustText = lv_label_create(ui_BrightnessPanel);
    lv_obj_set_width(ui_BrightnessAndjustText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessAndjustText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessAndjustText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessAndjustText, "Brightness");
    lv_obj_set_style_text_font(ui_BrightnessAndjustText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateTimePanel = lv_obj_create(ui_OptionsScreenPanel);
    lv_obj_set_width(ui_DateTimePanel, 421);
    lv_obj_set_height(ui_DateTimePanel, 29);
    lv_obj_set_x(ui_DateTimePanel, 0);
    lv_obj_set_y(ui_DateTimePanel, -43);
    lv_obj_set_align(ui_DateTimePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DateTimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DateTimeText = lv_label_create(ui_DateTimePanel);
    lv_obj_set_width(ui_DateTimeText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateTimeText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DateTimeText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateTimeText, "Date/Time");
    lv_obj_set_style_text_font(ui_DateTimeText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbtn3 = lv_img_create(ui_OptionsScreenPanel);
    lv_img_set_src(ui_backbtn3, &ui_img_1803534315);
    lv_obj_set_width(ui_backbtn3, 50);
    lv_obj_set_height(ui_backbtn3, 50);
    lv_obj_set_x(ui_backbtn3, -190);
    lv_obj_set_y(ui_backbtn3, 135);
    lv_obj_set_align(ui_backbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backbtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_backbtn3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_primaryBlue);
    ui_object_set_themeable_style_property(ui_backbtn3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_primaryBlue);

    lv_obj_add_event_cb(ui_WiFiOptionsText, ui_event_WiFiOptionsText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiPanel, ui_event_WiFiPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrightnessAndjustText, ui_event_BrightnessAndjustText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrightnessPanel, ui_event_BrightnessPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DateTimeText, ui_event_DateTimeText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DateTimePanel, ui_event_DateTimePanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backbtn3, ui_event_backbtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OptionsScreen, ui_event_OptionsScreen, LV_EVENT_ALL, NULL);

}

void ui_OptionsScreen_screen_destroy(void)
{
    if(ui_OptionsScreen) lv_obj_del(ui_OptionsScreen);

    // NULL screen variables
    ui_OptionsScreen = NULL;
    ui_OptionsScreenPanel = NULL;
    ui_WiFiPanel = NULL;
    ui_WiFiOptionsText = NULL;
    ui_BrightnessPanel = NULL;
    ui_BrightnessAndjustText = NULL;
    ui_DateTimePanel = NULL;
    ui_DateTimeText = NULL;
    ui_backbtn3 = NULL;

}
