// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#ifndef UI_SENSORSDATASCREEN_H
#define UI_SENSORSDATASCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SensorsDataScreen
extern void ui_SensorsDataScreen_screen_init(void);
extern void ui_SensorsDataScreen_screen_destroy(void);
extern lv_obj_t * ui_SensorsDataScreen;
extern lv_obj_t * ui_SensorsDataScreenPanel;
extern lv_obj_t * ui_NameScreenPanel;
extern lv_obj_t * ui_NameScreenLbl;
extern lv_obj_t * ui_TimePanel1;
extern lv_obj_t * ui_Hourlbl;
extern lv_obj_t * ui_Center;
extern lv_obj_t * ui_Minutlbl;
extern lv_obj_t * ui_DatePanel1;
extern lv_obj_t * ui_Datelbl;
extern lv_obj_t * ui_AQIPanel;
extern lv_obj_t * ui_NamePanelAQI;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_AQIArc;
extern lv_obj_t * ui_AQILabel;
extern lv_obj_t * ui_TVOCPanel;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TVOClbl;
extern lv_obj_t * ui_CO2Panel;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_CO2lbl;
extern lv_obj_t * ui_SensorsDataPanel;
extern lv_obj_t * ui_NamePanelSensors;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_TempHumPanel;
extern lv_obj_t * ui_TempHum;
extern lv_obj_t * ui_Templbl;
extern lv_obj_t * ui_celsiustext3;
extern lv_obj_t * ui_Humlbl;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_BarometerPanel;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Pressurelbl;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_AltitudeAboveSeaLbl;
extern void ui_event_backbtn6(lv_event_t * e);
extern lv_obj_t * ui_backbtn6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

