// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#include "../ui.h"

lv_obj_t * ui_SensorsDataScreen = NULL;
lv_obj_t * ui_SensorsDataScreenPanel = NULL;
lv_obj_t * ui_NameScreenPanel = NULL;
lv_obj_t * ui_NameScreenLbl = NULL;
lv_obj_t * ui_TimePanel1 = NULL;
lv_obj_t * ui_Hourlbl = NULL;
lv_obj_t * ui_Center = NULL;
lv_obj_t * ui_Minutlbl = NULL;
lv_obj_t * ui_DatePanel1 = NULL;
lv_obj_t * ui_Datelbl = NULL;
lv_obj_t * ui_AQIPanel = NULL;
lv_obj_t * ui_NamePanelAQI = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_AQIArc = NULL;
lv_obj_t * ui_AQILabel = NULL;
lv_obj_t * ui_TVOCPanel = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_TVOClbl = NULL;
lv_obj_t * ui_CO2Panel = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_CO2lbl = NULL;
lv_obj_t * ui_SensorsDataPanel = NULL;
lv_obj_t * ui_NamePanelSensors = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_TempHumPanel = NULL;
lv_obj_t * ui_TempHum = NULL;
lv_obj_t * ui_Templbl = NULL;
lv_obj_t * ui_celsiustext3 = NULL;
lv_obj_t * ui_Humlbl = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_BarometerPanel = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Pressurelbl = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_AltitudeAboveSeaLbl = NULL;
lv_obj_t * ui_backbtn6 = NULL;
// event funtions
void ui_event_backbtn6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 100, 0, &ui_MainScreen_screen_init);
    }
}

// build funtions

void ui_SensorsDataScreen_screen_init(void)
{
    ui_SensorsDataScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SensorsDataScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SensorsDataScreenPanel = lv_obj_create(ui_SensorsDataScreen);
    lv_obj_set_width(ui_SensorsDataScreenPanel, 480);
    lv_obj_set_height(ui_SensorsDataScreenPanel, 320);
    lv_obj_set_align(ui_SensorsDataScreenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SensorsDataScreenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SensorsDataScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SensorsDataScreenPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SensorsDataScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SensorsDataScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameScreenPanel = lv_obj_create(ui_SensorsDataScreenPanel);
    lv_obj_set_width(ui_NameScreenPanel, lv_pct(40));
    lv_obj_set_height(ui_NameScreenPanel, lv_pct(20));
    lv_obj_set_x(ui_NameScreenPanel, 0);
    lv_obj_set_y(ui_NameScreenPanel, -45);
    lv_obj_set_align(ui_NameScreenPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_NameScreenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NameScreenLbl = lv_label_create(ui_NameScreenPanel);
    lv_obj_set_width(ui_NameScreenLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameScreenLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameScreenLbl, 0);
    lv_obj_set_y(ui_NameScreenLbl, 10);
    lv_obj_set_align(ui_NameScreenLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NameScreenLbl, "Sensors data");

    ui_TimePanel1 = lv_obj_create(ui_SensorsDataScreenPanel);
    lv_obj_set_height(ui_TimePanel1, 32);
    lv_obj_set_width(ui_TimePanel1, lv_pct(25));
    lv_obj_set_x(ui_TimePanel1, -20);
    lv_obj_set_y(ui_TimePanel1, -20);
    lv_obj_clear_flag(ui_TimePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Hourlbl = lv_label_create(ui_TimePanel1);
    lv_obj_set_width(ui_Hourlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hourlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Hourlbl, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Hourlbl, "23");
    lv_obj_set_style_text_font(ui_Hourlbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Center = lv_label_create(ui_TimePanel1);
    lv_obj_set_width(ui_Center, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Center, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Center, -10);
    lv_obj_set_y(ui_Center, 0);
    lv_obj_set_align(ui_Center, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Center, ":");
    lv_obj_set_style_text_font(ui_Center, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minutlbl = lv_label_create(ui_TimePanel1);
    lv_obj_set_width(ui_Minutlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Minutlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Minutlbl, 5);
    lv_obj_set_y(ui_Minutlbl, 0);
    lv_obj_set_align(ui_Minutlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Minutlbl, "12");
    lv_obj_set_style_text_font(ui_Minutlbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DatePanel1 = lv_obj_create(ui_SensorsDataScreenPanel);
    lv_obj_set_height(ui_DatePanel1, 32);
    lv_obj_set_width(ui_DatePanel1, lv_pct(25));
    lv_obj_set_x(ui_DatePanel1, 20);
    lv_obj_set_y(ui_DatePanel1, -20);
    lv_obj_set_align(ui_DatePanel1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_DatePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Datelbl = lv_label_create(ui_DatePanel1);
    lv_obj_set_width(ui_Datelbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Datelbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Datelbl, -5);
    lv_obj_set_y(ui_Datelbl, 0);
    lv_obj_set_align(ui_Datelbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Datelbl, "2024.01.01");
    lv_obj_set_style_text_font(ui_Datelbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AQIPanel = lv_obj_create(ui_SensorsDataScreenPanel);
    lv_obj_set_width(ui_AQIPanel, 240);
    lv_obj_set_height(ui_AQIPanel, lv_pct(85));
    lv_obj_set_x(ui_AQIPanel, -10);
    lv_obj_set_y(ui_AQIPanel, 5);
    lv_obj_set_align(ui_AQIPanel, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_AQIPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AQIPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AQIPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AQIPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AQIPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NamePanelAQI = lv_obj_create(ui_AQIPanel);
    lv_obj_set_width(ui_NamePanelAQI, 100);
    lv_obj_set_height(ui_NamePanelAQI, 50);
    lv_obj_set_x(ui_NamePanelAQI, 0);
    lv_obj_set_y(ui_NamePanelAQI, -35);
    lv_obj_set_align(ui_NamePanelAQI, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_NamePanelAQI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_NamePanelAQI);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "AQI");

    ui_AQIArc = lv_arc_create(ui_AQIPanel);
    lv_obj_set_width(ui_AQIArc, 150);
    lv_obj_set_height(ui_AQIArc, 150);
    lv_obj_set_x(ui_AQIArc, 0);
    lv_obj_set_y(ui_AQIArc, 20);
    lv_obj_set_align(ui_AQIArc, LV_ALIGN_TOP_MID);
    lv_arc_set_range(ui_AQIArc, 1, 5);
    lv_arc_set_value(ui_AQIArc, 3);

    lv_obj_set_style_bg_grad_dir(ui_AQIArc, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_AQIArc, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_AQIArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_AQIArc, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_AQIArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_AQIArc, LV_BORDER_SIDE_NONE, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_AQILabel = lv_label_create(ui_AQIArc);
    lv_obj_set_width(ui_AQILabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AQILabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AQILabel, -1);
    lv_obj_set_y(ui_AQILabel, 1);
    lv_obj_set_align(ui_AQILabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AQILabel, "Normal");

    ui_TVOCPanel = lv_obj_create(ui_AQIPanel);
    lv_obj_set_width(ui_TVOCPanel, 115);
    lv_obj_set_height(ui_TVOCPanel, 50);
    lv_obj_set_x(ui_TVOCPanel, -15);
    lv_obj_set_y(ui_TVOCPanel, 0);
    lv_obj_set_align(ui_TVOCPanel, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_TVOCPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_TVOCPanel);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -15);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label3, "TVOC:");

    ui_TVOClbl = lv_label_create(ui_TVOCPanel);
    lv_obj_set_width(ui_TVOClbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TVOClbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TVOClbl, 30);
    lv_obj_set_y(ui_TVOClbl, 0);
    lv_obj_set_align(ui_TVOClbl, LV_ALIGN_BOTTOM_LEFT);

    ui_CO2Panel = lv_obj_create(ui_AQIPanel);
    lv_obj_set_width(ui_CO2Panel, 115);
    lv_obj_set_height(ui_CO2Panel, 50);
    lv_obj_set_x(ui_CO2Panel, 15);
    lv_obj_set_y(ui_CO2Panel, 0);
    lv_obj_set_align(ui_CO2Panel, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_CO2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_CO2Panel);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -15);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label1, "eCO2:");

    ui_CO2lbl = lv_label_create(ui_CO2Panel);
    lv_obj_set_width(ui_CO2lbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2lbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2lbl, 30);
    lv_obj_set_y(ui_CO2lbl, 0);
    lv_obj_set_align(ui_CO2lbl, LV_ALIGN_BOTTOM_LEFT);

    ui_SensorsDataPanel = lv_obj_create(ui_SensorsDataScreenPanel);
    lv_obj_set_width(ui_SensorsDataPanel, 240);
    lv_obj_set_height(ui_SensorsDataPanel, lv_pct(85));
    lv_obj_set_x(ui_SensorsDataPanel, 10);
    lv_obj_set_y(ui_SensorsDataPanel, 5);
    lv_obj_set_align(ui_SensorsDataPanel, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_SensorsDataPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SensorsDataPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SensorsDataPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SensorsDataPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SensorsDataPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NamePanelSensors = lv_obj_create(ui_SensorsDataPanel);
    lv_obj_set_width(ui_NamePanelSensors, 100);
    lv_obj_set_height(ui_NamePanelSensors, 50);
    lv_obj_set_x(ui_NamePanelSensors, 0);
    lv_obj_set_y(ui_NamePanelSensors, -35);
    lv_obj_set_align(ui_NamePanelSensors, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_NamePanelSensors, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_NamePanelSensors);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Sensors");

    ui_TempHumPanel = lv_obj_create(ui_SensorsDataPanel);
    lv_obj_set_width(ui_TempHumPanel, 150);
    lv_obj_set_height(ui_TempHumPanel, 100);
    lv_obj_set_x(ui_TempHumPanel, 0);
    lv_obj_set_y(ui_TempHumPanel, 20);
    lv_obj_set_align(ui_TempHumPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TempHumPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempHum = lv_img_create(ui_TempHumPanel);
    lv_img_set_src(ui_TempHum, &ui_img_temphum_png);
    lv_obj_set_width(ui_TempHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempHum, -42);
    lv_obj_set_y(ui_TempHum, 25);
    lv_obj_set_align(ui_TempHum, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_TempHum, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TempHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_TempHum, 150);

    ui_Templbl = lv_label_create(ui_TempHumPanel);
    lv_obj_set_width(ui_Templbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Templbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Templbl, 45);
    lv_obj_set_y(ui_Templbl, 10);
    lv_label_set_text(ui_Templbl, "24.2");
    lv_obj_set_style_text_font(ui_Templbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_celsiustext3 = lv_label_create(ui_TempHumPanel);
    lv_obj_set_width(ui_celsiustext3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_celsiustext3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_celsiustext3, 0);
    lv_obj_set_y(ui_celsiustext3, 10);
    lv_obj_set_align(ui_celsiustext3, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_celsiustext3, "°C");
    lv_obj_set_style_text_font(ui_celsiustext3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humlbl = lv_label_create(ui_TempHumPanel);
    lv_obj_set_width(ui_Humlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humlbl, 45);
    lv_obj_set_y(ui_Humlbl, -10);
    lv_obj_set_align(ui_Humlbl, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Humlbl, "40");
    lv_obj_set_style_text_font(ui_Humlbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_TempHumPanel);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -25);
    lv_obj_set_y(ui_Label8, 11);
    lv_obj_set_align(ui_Label8, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label8, "%");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarometerPanel = lv_obj_create(ui_SensorsDataPanel);
    lv_obj_set_width(ui_BarometerPanel, 150);
    lv_obj_set_height(ui_BarometerPanel, 100);
    lv_obj_set_x(ui_BarometerPanel, 0);
    lv_obj_set_y(ui_BarometerPanel, 14);
    lv_obj_set_align(ui_BarometerPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_BarometerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_BarometerPanel);
    lv_img_set_src(ui_Image2, &ui_img_barometer_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -53);
    lv_obj_set_y(ui_Image2, -20);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 20);

    ui_Pressurelbl = lv_label_create(ui_BarometerPanel);
    lv_obj_set_width(ui_Pressurelbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pressurelbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pressurelbl, 30);
    lv_obj_set_y(ui_Pressurelbl, -40);
    lv_obj_set_align(ui_Pressurelbl, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Pressurelbl, "298");

    ui_Image1 = lv_img_create(ui_BarometerPanel);
    lv_img_set_src(ui_Image1, &ui_img_1387918458);
    lv_obj_set_width(ui_Image1, 48);
    lv_obj_set_height(ui_Image1, 48);
    lv_obj_set_x(ui_Image1, -20);
    lv_obj_set_y(ui_Image1, 15);
    lv_obj_set_align(ui_Image1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AltitudeAboveSeaLbl = lv_label_create(ui_BarometerPanel);
    lv_obj_set_width(ui_AltitudeAboveSeaLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeAboveSeaLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AltitudeAboveSeaLbl, 30);
    lv_obj_set_y(ui_AltitudeAboveSeaLbl, 5);
    lv_obj_set_align(ui_AltitudeAboveSeaLbl, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_AltitudeAboveSeaLbl, "298 m");

    ui_backbtn6 = lv_img_create(ui_SensorsDataScreen);
    lv_img_set_src(ui_backbtn6, &ui_img_1803534315);
    lv_obj_set_width(ui_backbtn6, 50);
    lv_obj_set_height(ui_backbtn6, 50);
    lv_obj_set_x(ui_backbtn6, -190);
    lv_obj_set_y(ui_backbtn6, 145);
    lv_obj_set_align(ui_backbtn6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backbtn6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_backbtn6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_primaryBlue);
    ui_object_set_themeable_style_property(ui_backbtn6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_primaryBlue);

    lv_obj_add_event_cb(ui_backbtn6, ui_event_backbtn6, LV_EVENT_ALL, NULL);

}

void ui_SensorsDataScreen_screen_destroy(void)
{
    if(ui_SensorsDataScreen) lv_obj_del(ui_SensorsDataScreen);

    // NULL screen variables
    ui_SensorsDataScreen = NULL;
    ui_SensorsDataScreenPanel = NULL;
    ui_NameScreenPanel = NULL;
    ui_NameScreenLbl = NULL;
    ui_TimePanel1 = NULL;
    ui_Hourlbl = NULL;
    ui_Center = NULL;
    ui_Minutlbl = NULL;
    ui_DatePanel1 = NULL;
    ui_Datelbl = NULL;
    ui_AQIPanel = NULL;
    ui_NamePanelAQI = NULL;
    ui_Label5 = NULL;
    ui_AQIArc = NULL;
    ui_AQILabel = NULL;
    ui_TVOCPanel = NULL;
    ui_Label3 = NULL;
    ui_TVOClbl = NULL;
    ui_CO2Panel = NULL;
    ui_Label1 = NULL;
    ui_CO2lbl = NULL;
    ui_SensorsDataPanel = NULL;
    ui_NamePanelSensors = NULL;
    ui_Label6 = NULL;
    ui_TempHumPanel = NULL;
    ui_TempHum = NULL;
    ui_Templbl = NULL;
    ui_celsiustext3 = NULL;
    ui_Humlbl = NULL;
    ui_Label8 = NULL;
    ui_BarometerPanel = NULL;
    ui_Image2 = NULL;
    ui_Pressurelbl = NULL;
    ui_Image1 = NULL;
    ui_AltitudeAboveSeaLbl = NULL;
    ui_backbtn6 = NULL;

}
