// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#ifndef UI_WEATHERSCREEN_H
#define UI_WEATHERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WeatherScreen
extern void ui_WeatherScreen_screen_init(void);
extern void ui_WeatherScreen_screen_destroy(void);
extern lv_obj_t * ui_WeatherScreen;
extern lv_obj_t * ui_WeatherScreenPanel;
extern lv_obj_t * ui_NameScreenPanel1;
extern lv_obj_t * ui_NameScreenLbl1;
extern lv_obj_t * ui_TimePanel2;
extern lv_obj_t * ui_Hourlbl1;
extern lv_obj_t * ui_Center1;
extern lv_obj_t * ui_Minutlbl1;
extern lv_obj_t * ui_TodayPanel;
extern lv_obj_t * ui_DayName;
extern lv_obj_t * ui_TodayImg;
extern lv_obj_t * ui_weatherInfoToday;
extern lv_obj_t * ui_TodayHumLabel;
extern lv_obj_t * ui_TodayTempLabel;
extern lv_obj_t * ui_DatePanel2;
extern lv_obj_t * ui_Datelbl1;
extern lv_obj_t * ui_TomorrowPanel;
extern lv_obj_t * ui_DayName1;
extern lv_obj_t * ui_TomorrowImg;
extern lv_obj_t * ui_weatherInfoTomorraw;
extern lv_obj_t * ui_TomorrowHumLabel;
extern lv_obj_t * ui_TomorrowTempLabel;
extern lv_obj_t * ui_TheDayAfterTomorrowPanel;
extern lv_obj_t * ui_DayName2;
extern lv_obj_t * ui_TheDayAfterTomorrowImg;
extern lv_obj_t * ui_weatherInfoTheDayAfterTomorrow;
extern lv_obj_t * ui_AfterTomorrowHumLabel;
extern lv_obj_t * ui_AfterTomorrowTempLabel;
extern void ui_event_backbtn7(lv_event_t * e);
extern lv_obj_t * ui_backbtn7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

