// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#include "../ui.h"

lv_obj_t * ui_WeatherScreen = NULL;
lv_obj_t * ui_WeatherScreenPanel = NULL;
lv_obj_t * ui_NameScreenPanel1 = NULL;
lv_obj_t * ui_NameScreenLbl1 = NULL;
lv_obj_t * ui_TimePanel2 = NULL;
lv_obj_t * ui_Hourlbl1 = NULL;
lv_obj_t * ui_Center1 = NULL;
lv_obj_t * ui_Minutlbl1 = NULL;
lv_obj_t * ui_TodayPanel = NULL;
lv_obj_t * ui_DayName = NULL;
lv_obj_t * ui_TodayImg = NULL;
lv_obj_t * ui_weatherInfoToday = NULL;
lv_obj_t * ui_TodayHumLabel = NULL;
lv_obj_t * ui_TodayTempLabel = NULL;
lv_obj_t * ui_DatePanel2 = NULL;
lv_obj_t * ui_Datelbl1 = NULL;
lv_obj_t * ui_TomorrowPanel = NULL;
lv_obj_t * ui_DayName1 = NULL;
lv_obj_t * ui_TomorrowImg = NULL;
lv_obj_t * ui_weatherInfoTomorraw = NULL;
lv_obj_t * ui_TomorrowHumLabel = NULL;
lv_obj_t * ui_TomorrowTempLabel = NULL;
lv_obj_t * ui_TheDayAfterTomorrowPanel = NULL;
lv_obj_t * ui_DayName2 = NULL;
lv_obj_t * ui_TheDayAfterTomorrowImg = NULL;
lv_obj_t * ui_weatherInfoTheDayAfterTomorrow = NULL;
lv_obj_t * ui_AfterTomorrowHumLabel = NULL;
lv_obj_t * ui_AfterTomorrowTempLabel = NULL;
lv_obj_t * ui_backbtn7 = NULL;
// event funtions
void ui_event_backbtn7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 100, 0, &ui_MainScreen_screen_init);
    }
}

// build funtions

void ui_WeatherScreen_screen_init(void)
{
    ui_WeatherScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WeatherScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherScreenPanel = lv_obj_create(ui_WeatherScreen);
    lv_obj_set_width(ui_WeatherScreenPanel, 480);
    lv_obj_set_height(ui_WeatherScreenPanel, 320);
    lv_obj_set_align(ui_WeatherScreenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WeatherScreenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WeatherScreenPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WeatherScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameScreenPanel1 = lv_obj_create(ui_WeatherScreenPanel);
    lv_obj_set_width(ui_NameScreenPanel1, lv_pct(40));
    lv_obj_set_height(ui_NameScreenPanel1, lv_pct(20));
    lv_obj_set_x(ui_NameScreenPanel1, 0);
    lv_obj_set_y(ui_NameScreenPanel1, -45);
    lv_obj_set_align(ui_NameScreenPanel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_NameScreenPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NameScreenLbl1 = lv_label_create(ui_NameScreenPanel1);
    lv_obj_set_width(ui_NameScreenLbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameScreenLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameScreenLbl1, 0);
    lv_obj_set_y(ui_NameScreenLbl1, 10);
    lv_obj_set_align(ui_NameScreenLbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NameScreenLbl1, "Weather forecast");

    ui_TimePanel2 = lv_obj_create(ui_WeatherScreenPanel);
    lv_obj_set_height(ui_TimePanel2, 32);
    lv_obj_set_width(ui_TimePanel2, lv_pct(25));
    lv_obj_set_x(ui_TimePanel2, -20);
    lv_obj_set_y(ui_TimePanel2, -20);
    lv_obj_clear_flag(ui_TimePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Hourlbl1 = lv_label_create(ui_TimePanel2);
    lv_obj_set_width(ui_Hourlbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hourlbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Hourlbl1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Hourlbl1, "23");
    lv_obj_set_style_text_font(ui_Hourlbl1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Center1 = lv_label_create(ui_TimePanel2);
    lv_obj_set_width(ui_Center1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Center1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Center1, -10);
    lv_obj_set_y(ui_Center1, 0);
    lv_obj_set_align(ui_Center1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Center1, ":");
    lv_obj_set_style_text_font(ui_Center1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minutlbl1 = lv_label_create(ui_TimePanel2);
    lv_obj_set_width(ui_Minutlbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Minutlbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Minutlbl1, 5);
    lv_obj_set_y(ui_Minutlbl1, 0);
    lv_obj_set_align(ui_Minutlbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Minutlbl1, "12");
    lv_obj_set_style_text_font(ui_Minutlbl1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TodayPanel = lv_obj_create(ui_WeatherScreenPanel);
    lv_obj_set_width(ui_TodayPanel, lv_pct(30));
    lv_obj_set_height(ui_TodayPanel, lv_pct(80));
    lv_obj_set_x(ui_TodayPanel, 0);
    lv_obj_set_y(ui_TodayPanel, 30);
    lv_obj_clear_flag(ui_TodayPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DayName = lv_label_create(ui_TodayPanel);
    lv_obj_set_width(ui_DayName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DayName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DayName, 0);
    lv_obj_set_y(ui_DayName, -10);
    lv_obj_set_align(ui_DayName, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DayName, "Today");

    ui_TodayImg = lv_img_create(ui_TodayPanel);
    lv_img_set_src(ui_TodayImg, &ui_img_1410116608);
    lv_obj_set_width(ui_TodayImg, lv_pct(90));
    lv_obj_set_height(ui_TodayImg, lv_pct(60));
    lv_obj_set_x(ui_TodayImg, -5);
    lv_obj_set_y(ui_TodayImg, 0);
    lv_obj_set_align(ui_TodayImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TodayImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TodayImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weatherInfoToday = lv_label_create(ui_TodayPanel);
    lv_obj_set_width(ui_weatherInfoToday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherInfoToday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_weatherInfoToday, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_weatherInfoToday, "BrokenClouds");

    ui_TodayHumLabel = lv_label_create(ui_TodayPanel);
    lv_obj_set_width(ui_TodayHumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TodayHumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TodayHumLabel, 10);
    lv_obj_set_y(ui_TodayHumLabel, -40);
    lv_obj_set_align(ui_TodayHumLabel, LV_ALIGN_BOTTOM_RIGHT);

    ui_TodayTempLabel = lv_label_create(ui_TodayPanel);
    lv_obj_set_width(ui_TodayTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TodayTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TodayTempLabel, -10);
    lv_obj_set_y(ui_TodayTempLabel, -40);
    lv_obj_set_align(ui_TodayTempLabel, LV_ALIGN_BOTTOM_LEFT);

    ui_DatePanel2 = lv_obj_create(ui_WeatherScreenPanel);
    lv_obj_set_height(ui_DatePanel2, 32);
    lv_obj_set_width(ui_DatePanel2, lv_pct(25));
    lv_obj_set_x(ui_DatePanel2, 20);
    lv_obj_set_y(ui_DatePanel2, -20);
    lv_obj_set_align(ui_DatePanel2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_DatePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Datelbl1 = lv_label_create(ui_DatePanel2);
    lv_obj_set_width(ui_Datelbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Datelbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Datelbl1, -5);
    lv_obj_set_y(ui_Datelbl1, 0);
    lv_obj_set_align(ui_Datelbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Datelbl1, "2024.01.01");
    lv_obj_set_style_text_font(ui_Datelbl1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TomorrowPanel = lv_obj_create(ui_WeatherScreenPanel);
    lv_obj_set_width(ui_TomorrowPanel, lv_pct(30));
    lv_obj_set_height(ui_TomorrowPanel, lv_pct(80));
    lv_obj_set_align(ui_TomorrowPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TomorrowPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DayName1 = lv_label_create(ui_TomorrowPanel);
    lv_obj_set_width(ui_DayName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DayName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DayName1, 0);
    lv_obj_set_y(ui_DayName1, -10);
    lv_obj_set_align(ui_DayName1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DayName1, "Tomorrow");

    ui_TomorrowImg = lv_img_create(ui_TomorrowPanel);
    lv_img_set_src(ui_TomorrowImg, &ui_img_1410116608);
    lv_obj_set_width(ui_TomorrowImg, lv_pct(90));
    lv_obj_set_height(ui_TomorrowImg, lv_pct(60));
    lv_obj_set_x(ui_TomorrowImg, -5);
    lv_obj_set_y(ui_TomorrowImg, 0);
    lv_obj_set_align(ui_TomorrowImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TomorrowImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TomorrowImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weatherInfoTomorraw = lv_label_create(ui_TomorrowPanel);
    lv_obj_set_width(ui_weatherInfoTomorraw, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherInfoTomorraw, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_weatherInfoTomorraw, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_weatherInfoTomorraw, "BrokenClouds");

    ui_TomorrowHumLabel = lv_label_create(ui_TomorrowPanel);
    lv_obj_set_width(ui_TomorrowHumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TomorrowHumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TomorrowHumLabel, 10);
    lv_obj_set_y(ui_TomorrowHumLabel, -40);
    lv_obj_set_align(ui_TomorrowHumLabel, LV_ALIGN_BOTTOM_RIGHT);

    ui_TomorrowTempLabel = lv_label_create(ui_TomorrowPanel);
    lv_obj_set_width(ui_TomorrowTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TomorrowTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TomorrowTempLabel, -10);
    lv_obj_set_y(ui_TomorrowTempLabel, -40);
    lv_obj_set_align(ui_TomorrowTempLabel, LV_ALIGN_BOTTOM_LEFT);

    ui_TheDayAfterTomorrowPanel = lv_obj_create(ui_WeatherScreenPanel);
    lv_obj_set_width(ui_TheDayAfterTomorrowPanel, lv_pct(30));
    lv_obj_set_height(ui_TheDayAfterTomorrowPanel, lv_pct(80));
    lv_obj_set_x(ui_TheDayAfterTomorrowPanel, 0);
    lv_obj_set_y(ui_TheDayAfterTomorrowPanel, 30);
    lv_obj_set_align(ui_TheDayAfterTomorrowPanel, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_TheDayAfterTomorrowPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DayName2 = lv_label_create(ui_TheDayAfterTomorrowPanel);
    lv_obj_set_width(ui_DayName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DayName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DayName2, 0);
    lv_obj_set_y(ui_DayName2, -10);
    lv_obj_set_align(ui_DayName2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DayName2, "	     The day\nafter tomorrow");

    ui_TheDayAfterTomorrowImg = lv_img_create(ui_TheDayAfterTomorrowPanel);
    lv_img_set_src(ui_TheDayAfterTomorrowImg, &ui_img_1410116608);
    lv_obj_set_width(ui_TheDayAfterTomorrowImg, lv_pct(90));
    lv_obj_set_height(ui_TheDayAfterTomorrowImg, lv_pct(60));
    lv_obj_set_x(ui_TheDayAfterTomorrowImg, -5);
    lv_obj_set_y(ui_TheDayAfterTomorrowImg, 0);
    lv_obj_set_align(ui_TheDayAfterTomorrowImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TheDayAfterTomorrowImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TheDayAfterTomorrowImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weatherInfoTheDayAfterTomorrow = lv_label_create(ui_TheDayAfterTomorrowPanel);
    lv_obj_set_width(ui_weatherInfoTheDayAfterTomorrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherInfoTheDayAfterTomorrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_weatherInfoTheDayAfterTomorrow, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_weatherInfoTheDayAfterTomorrow, "BrokenClouds");

    ui_AfterTomorrowHumLabel = lv_label_create(ui_TheDayAfterTomorrowPanel);
    lv_obj_set_width(ui_AfterTomorrowHumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AfterTomorrowHumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AfterTomorrowHumLabel, 10);
    lv_obj_set_y(ui_AfterTomorrowHumLabel, -40);
    lv_obj_set_align(ui_AfterTomorrowHumLabel, LV_ALIGN_BOTTOM_RIGHT);

    ui_AfterTomorrowTempLabel = lv_label_create(ui_TheDayAfterTomorrowPanel);
    lv_obj_set_width(ui_AfterTomorrowTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AfterTomorrowTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AfterTomorrowTempLabel, -10);
    lv_obj_set_y(ui_AfterTomorrowTempLabel, -40);
    lv_obj_set_align(ui_AfterTomorrowTempLabel, LV_ALIGN_BOTTOM_LEFT);

    ui_backbtn7 = lv_img_create(ui_WeatherScreen);
    lv_img_set_src(ui_backbtn7, &ui_img_1803534315);
    lv_obj_set_width(ui_backbtn7, 50);
    lv_obj_set_height(ui_backbtn7, 50);
    lv_obj_set_x(ui_backbtn7, -190);
    lv_obj_set_y(ui_backbtn7, 135);
    lv_obj_set_align(ui_backbtn7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backbtn7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_backbtn7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_primaryBlue);
    ui_object_set_themeable_style_property(ui_backbtn7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_primaryBlue);

    lv_obj_add_event_cb(ui_backbtn7, ui_event_backbtn7, LV_EVENT_ALL, NULL);

}

void ui_WeatherScreen_screen_destroy(void)
{
    if(ui_WeatherScreen) lv_obj_del(ui_WeatherScreen);

    // NULL screen variables
    ui_WeatherScreen = NULL;
    ui_WeatherScreenPanel = NULL;
    ui_NameScreenPanel1 = NULL;
    ui_NameScreenLbl1 = NULL;
    ui_TimePanel2 = NULL;
    ui_Hourlbl1 = NULL;
    ui_Center1 = NULL;
    ui_Minutlbl1 = NULL;
    ui_TodayPanel = NULL;
    ui_DayName = NULL;
    ui_TodayImg = NULL;
    ui_weatherInfoToday = NULL;
    ui_TodayHumLabel = NULL;
    ui_TodayTempLabel = NULL;
    ui_DatePanel2 = NULL;
    ui_Datelbl1 = NULL;
    ui_TomorrowPanel = NULL;
    ui_DayName1 = NULL;
    ui_TomorrowImg = NULL;
    ui_weatherInfoTomorraw = NULL;
    ui_TomorrowHumLabel = NULL;
    ui_TomorrowTempLabel = NULL;
    ui_TheDayAfterTomorrowPanel = NULL;
    ui_DayName2 = NULL;
    ui_TheDayAfterTomorrowImg = NULL;
    ui_weatherInfoTheDayAfterTomorrow = NULL;
    ui_AfterTomorrowHumLabel = NULL;
    ui_AfterTomorrowTempLabel = NULL;
    ui_backbtn7 = NULL;

}
