// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#ifndef UI_WIFISCREEN_H
#define UI_WIFISCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WiFiScreen
extern void ui_WiFiScreen_screen_init(void);
extern void ui_WiFiScreen_screen_destroy(void);
extern lv_obj_t * ui_WiFiScreen;
extern lv_obj_t * ui_WifiPanel1;
extern lv_obj_t * ui_WiFiText;
extern lv_obj_t * ui_Wifisw;
extern void ui_event_backbtn4(lv_event_t * e);
extern lv_obj_t * ui_backbtn4;
extern lv_obj_t * ui_ClearWifibtn;
extern lv_obj_t * ui_Clear;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

