// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WT32-SC01-PLUS

#include "../ui.h"

lv_obj_t * ui_WiFiScreen = NULL;
lv_obj_t * ui_WifiPanel1 = NULL;
lv_obj_t * ui_WiFiText = NULL;
lv_obj_t * ui_Wifisw = NULL;
lv_obj_t * ui_backbtn4 = NULL;
lv_obj_t * ui_ClearWifibtn = NULL;
lv_obj_t * ui_Clear = NULL;
// event funtions
void ui_event_backbtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OptionsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_OptionsScreen_screen_init);
    }
}

// build funtions

void ui_WiFiScreen_screen_init(void)
{
    ui_WiFiScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WiFiScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiPanel1 = lv_obj_create(ui_WiFiScreen);
    lv_obj_set_width(ui_WifiPanel1, 421);
    lv_obj_set_height(ui_WifiPanel1, 29);
    lv_obj_set_x(ui_WifiPanel1, 0);
    lv_obj_set_y(ui_WifiPanel1, -83);
    lv_obj_set_align(ui_WifiPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiText = lv_label_create(ui_WifiPanel1);
    lv_obj_set_width(ui_WiFiText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiText, -176);
    lv_obj_set_y(ui_WiFiText, 0);
    lv_obj_set_align(ui_WiFiText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiText, "WiFi");
    lv_obj_set_style_text_font(ui_WiFiText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifisw = lv_switch_create(ui_WifiPanel1);
    lv_obj_set_width(ui_Wifisw, 57);
    lv_obj_set_height(ui_Wifisw, 25);
    lv_obj_set_x(ui_Wifisw, 170);
    lv_obj_set_y(ui_Wifisw, -1);
    lv_obj_set_align(ui_Wifisw, LV_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_Wifisw, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primaryBlue);
    ui_object_set_themeable_style_property(ui_Wifisw, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primaryBlue);

    lv_obj_set_style_bg_color(ui_Wifisw, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifisw, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_backbtn4 = lv_img_create(ui_WiFiScreen);
    lv_img_set_src(ui_backbtn4, &ui_img_1803534315);
    lv_obj_set_width(ui_backbtn4, 50);
    lv_obj_set_height(ui_backbtn4, 50);
    lv_obj_set_x(ui_backbtn4, -190);
    lv_obj_set_y(ui_backbtn4, 135);
    lv_obj_set_align(ui_backbtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backbtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_backbtn4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_primaryBlue);
    ui_object_set_themeable_style_property(ui_backbtn4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_primaryBlue);

    ui_ClearWifibtn = lv_btn_create(ui_WiFiScreen);
    lv_obj_set_height(ui_ClearWifibtn, 50);
    lv_obj_set_width(ui_ClearWifibtn, lv_pct(80));
    lv_obj_set_align(ui_ClearWifibtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClearWifibtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ClearWifibtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Clear = lv_label_create(ui_ClearWifibtn);
    lv_obj_set_width(ui_Clear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Clear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Clear, "Clear Wifi Settinsgs");
    lv_obj_set_style_text_font(ui_Clear, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backbtn4, ui_event_backbtn4, LV_EVENT_ALL, NULL);

}

void ui_WiFiScreen_screen_destroy(void)
{
    if(ui_WiFiScreen) lv_obj_del(ui_WiFiScreen);

    // NULL screen variables
    ui_WiFiScreen = NULL;
    ui_WifiPanel1 = NULL;
    ui_WiFiText = NULL;
    ui_Wifisw = NULL;
    ui_backbtn4 = NULL;
    ui_ClearWifibtn = NULL;
    ui_Clear = NULL;

}
